import crypto from "node:crypto";

const THREAD_ADJECTIVES = [
  "active",
  "adaptable",
  "advanced",
  "agile",
  "alert",
  "analytical",
  "ambient",
  "balanced",
  "bold",
  "brisk",
  "calm",
  "candid",
  "casual",
  "central",
  "civic",
  "classic",
  "clear",
  "clever",
  "coherent",
  "collaborative",
  "compact",
  "concrete",
  "cool",
  "cordial",
  "creative",
  "critical",
  "curious",
  "daily",
  "deep",
  "deliberate",
  "detailed",
  "direct",
  "dynamic",
  "eager",
  "early",
  "efficient",
  "elegant",
  "elevated",
  "energetic",
  "essential",
  "ethical",
  "exact",
  "expressive",
  "fair",
  "fast",
  "fearless",
  "flexible",
  "focused",
  "formal",
  "fresh",
  "friendly",
  "general",
  "gentle",
  "global",
  "genuine",
  "grounded",
  "hardy",
  "helpful",
  "honest",
  "humble",
  "ideal",
  "immersive",
  "informed",
  "intentional",
  "keen",
  "layered",
  "lean",
  "local",
  "logical",
  "lucid",
  "mature",
  "mindful",
  "modern",
  "neat",
  "nimble",
  "open",
  "orderly",
  "patient",
  "practical",
  "precise",
  "progressive",
  "prompt",
  "pure",
  "quick",
  "quiet",
  "rapid",
  "ready",
  "real",
  "reflective",
  "reliable",
  "resilient",
  "robust",
  "serious",
  "simple",
  "solid",
  "stable",
  "steady",
  "structured",
  "swift",
  "thorough",
  "timely",
  "transparent",
  "trusted",
  "unified",
  "useful",
  "versatile",
  "vivid",
  "warm",
  "wise",
  "workable",
];

const THREAD_NOUNS = [
  "agenda",
  "answer",
  "archive",
  "article",
  "blueprint",
  "brief",
  "bulletin",
  "case",
  "catalog",
  "challenge",
  "checklist",
  "chronicle",
  "collection",
  "commentary",
  "concept",
  "design",
  "digest",
  "discussion",
  "dossier",
  "draft",
  "edition",
  "entry",
  "example",
  "exchange",
  "explainer",
  "faq",
  "feedback",
  "forecast",
  "framework",
  "guide",
  "handbook",
  "idea",
  "insight",
  "journal",
  "log",
  "memo",
  "method",
  "milestone",
  "model",
  "narrative",
  "notes",
  "notebook",
  "observation",
  "outline",
  "overview",
  "pattern",
  "perspective",
  "pipeline",
  "plan",
  "playbook",
  "post",
  "practice",
  "primer",
  "process",
  "project",
  "proposal",
  "protocol",
  "question",
  "queue",
  "recap",
  "record",
  "reference",
  "report",
  "request",
  "review",
  "roadmap",
  "rubric",
  "scenario",
  "schedule",
  "script",
  "session",
  "sketch",
  "snapshot",
  "spec",
  "spotlight",
  "status",
  "story",
  "strategy",
  "study",
  "summary",
  "survey",
  "synthesis",
  "system",
  "tactic",
  "task",
  "technique",
  "template",
  "thread",
  "topic",
  "track",
  "transcript",
  "trend",
  "tutorial",
  "update",
  "variant",
  "walkthrough",
  "workflow",
  "worksheet",
];

export function slugifySubject(subject) {
  if (!subject) return "thread";
  const s = subject
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "")
    .replace(/-+/g, "-")
    .slice(0, 60);

  return s || "thread";
}

/**
 * Generates a readable token like "daily_topic".
 * This is the stable identifier used in the URL.
 */
export function makeThreadToken() {
  const adj = THREAD_ADJECTIVES[crypto.randomInt(0, THREAD_ADJECTIVES.length)];
  const noun = THREAD_NOUNS[crypto.randomInt(0, THREAD_NOUNS.length)];
  return `${adj}_${noun}`;
}

export function normalizeToken(token) {
  return String(token).toLowerCase();
}

export function isUniqueViolation(err) {
  return err && typeof err === "object" && err.code === "23505";
}
